api_platform:
    title: Hello API Platform
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
        html: ['text/html']
        multipart: ['multipart/form-data']
    
    # ✅ Patch formats pour les modifications (PUT/PATCH)
    patch_formats:
        json: ['application/merge-patch+json']
    
    # ✅ Activer Swagger/OpenAPI
    swagger:
        versions: [3]